<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        DB::table('bookings')->truncate();

        DB::table('bookings')->insert([
            [
                'id' => 1,
                'member_id' => 1,
                'member_user_id' => 2,
                'member_name' => 'Ahmad Aziz Wira Widodo',
                'member_email' => 'wira123widodo@gmail.com',
                'field_id' => 1,
                'field_name' => 'Lapangan Futsal A',
                'field_type' => 'Futsal',
                'booking_date' => Carbon::today()->addDay()->toDateString(),
                'start_time' => '09:00:00',
                'end_time' => '11:00:00',
                'duration_hours' => 2,
                'price_per_hour' => 150000,
                'total_price' => 300000,
                'status' => 'pending',
                'note' => 'Booking request untuk latihan futsal tim.',
                'rejection_reason' => null,
                'approved_at' => null,
                'rejected_at' => null,
                'canceled_at' => null,
                'approved_by' => null,
                'rejected_by' => null,
                'canceled_by' => null,
                'created_at' => $now->copy()->subHours(5),
                'updated_at' => $now->copy()->subHours(5),
            ],
            [
                'id' => 2,
                'member_id' => 2,
                'member_user_id' => 3,
                'member_name' => 'Aura Iftitah',
                'member_email' => 'auraiftitahh@gmail.com',
                'field_id' => 3,
                'field_name' => 'Lapangan Badminton A',
                'field_type' => 'Badminton',
                'booking_date' => Carbon::today()->addDays(2)->toDateString(),
                'start_time' => '13:00:00',
                'end_time' => '15:00:00',
                'duration_hours' => 2,
                'price_per_hour' => 75000,
                'total_price' => 150000,
                'status' => 'pending',
                'note' => 'Booking request untuk latihan badminton.',
                'rejection_reason' => null,
                'approved_at' => null,
                'rejected_at' => null,
                'canceled_at' => null,
                'approved_by' => null,
                'rejected_by' => null,
                'canceled_by' => null,
                'created_at' => $now->copy()->subHours(4),
                'updated_at' => $now->copy()->subHours(4),
            ],
            [
                'id' => 3,
                'member_id' => 3,
                'member_user_id' => 4,
                'member_name' => 'Muhammad Agil Hidayahtullah',
                'member_email' => 'muhammadagilhidayahtullah295@gmail.com',
                'field_id' => 2,
                'field_name' => 'Lapangan Futsal B',
                'field_type' => 'Futsal',
                'booking_date' => Carbon::today()->subDay()->toDateString(),
                'start_time' => '19:00:00',
                'end_time' => '21:00:00',
                'duration_hours' => 2,
                'price_per_hour' => 175000,
                'total_price' => 350000,
                'status' => 'approved',
                'note' => 'Booking yang sudah disetujui untuk simulasi riwayat.',
                'rejection_reason' => null,
                'approved_at' => $now->copy()->subHours(20),
                'rejected_at' => null,
                'canceled_at' => null,
                'approved_by' => 'Retobluto Admin',
                'rejected_by' => null,
                'canceled_by' => null,
                'created_at' => $now->copy()->subDays(2),
                'updated_at' => $now->copy()->subHours(20),
            ],
            [
                'id' => 4,
                'member_id' => 4,
                'member_user_id' => 5,
                'member_name' => 'Ryan Alvin Saputra',
                'member_email' => 'ryanalfin6@gmail.com',
                'field_id' => 4,
                'field_name' => 'Lapangan Basket A',
                'field_type' => 'Basket',
                'booking_date' => Carbon::today()->subDays(2)->toDateString(),
                'start_time' => '10:00:00',
                'end_time' => '12:00:00',
                'duration_hours' => 2,
                'price_per_hour' => 200000,
                'total_price' => 400000,
                'status' => 'rejected',
                'note' => 'Booking pada lapangan yang sedang maintenance.',
                'rejection_reason' => 'Lapangan sedang maintenance pada jadwal tersebut.',
                'approved_at' => null,
                'rejected_at' => $now->copy()->subDays(2)->addHours(2),
                'canceled_at' => null,
                'approved_by' => null,
                'rejected_by' => 'Retobluto Admin',
                'canceled_by' => null,
                'created_at' => $now->copy()->subDays(3),
                'updated_at' => $now->copy()->subDays(2)->addHours(2),
            ],
            [
                'id' => 5,
                'member_id' => 1,
                'member_user_id' => 2,
                'member_name' => 'Ahmad Aziz Wira Widodo',
                'member_email' => 'wira123widodo@gmail.com',
                'field_id' => 5,
                'field_name' => 'Lapangan Mini Soccer A',
                'field_type' => 'Mini Soccer',
                'booking_date' => Carbon::today()->subDays(3)->toDateString(),
                'start_time' => '16:00:00',
                'end_time' => '18:00:00',
                'duration_hours' => 2,
                'price_per_hour' => 250000,
                'total_price' => 500000,
                'status' => 'canceled',
                'note' => 'Booking yang dibatalkan oleh member.',
                'rejection_reason' => null,
                'approved_at' => null,
                'rejected_at' => null,
                'canceled_at' => $now->copy()->subDays(3)->addHours(1),
                'approved_by' => null,
                'rejected_by' => null,
                'canceled_by' => 'Ahmad Aziz Wira Widodo',
                'created_at' => $now->copy()->subDays(4),
                'updated_at' => $now->copy()->subDays(3)->addHours(1),
            ],
            [
                'id' => 6,
                'member_id' => 2,
                'member_user_id' => 3,
                'member_name' => 'Aura Iftitah',
                'member_email' => 'auraiftitahh@gmail.com',
                'field_id' => 1,
                'field_name' => 'Lapangan Futsal A',
                'field_type' => 'Futsal',
                'booking_date' => Carbon::today()->addDays(4)->toDateString(),
                'start_time' => '18:00:00',
                'end_time' => '20:00:00',
                'duration_hours' => 2,
                'price_per_hour' => 150000,
                'total_price' => 300000,
                'status' => 'approved',
                'note' => 'Booking approved untuk jadwal mendatang.',
                'rejection_reason' => null,
                'approved_at' => $now->copy()->subHours(2),
                'rejected_at' => null,
                'canceled_at' => null,
                'approved_by' => 'Retobluto Admin',
                'rejected_by' => null,
                'canceled_by' => null,
                'created_at' => $now->copy()->subHours(3),
                'updated_at' => $now->copy()->subHours(2),
            ],
        ]);
    }
}
